# Generated by Django 3.2.4 on 2021-06-27 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interview', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='interviewer',
            field=models.BooleanField(db_index=True, default=False),
        ),
    ]
