# Generated by Django 3.2.4 on 2021-06-27 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interview', '0002_person_interviewer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timeslot',
            name='from_time',
            field=models.TimeField(),
        ),
        migrations.AlterField(
            model_name='timeslot',
            name='to_time',
            field=models.TimeField(),
        ),
    ]
